import { BlockDefinition } from "./types";
import {
  ArrowUpCircle,
  Bell,
  CheckCircle,
  CheckCircle2,
  Circle,
  Clock,
  Cpu,
  Filter,
  GitBranch,
  Headphones,
  MessageSquare,
  PauseCircle,
  Play,
  PlayCircle,
  RotateCcw,
  ShieldCheck,
  Shuffle,
  SlidersHorizontal,
  User,
  UserCog,
} from "lucide-react";
export const BLOCKS: Record<string, BlockDefinition[]> = {
  Other: [
    {
      blockId: "start",
      label: "Start",
      type: "start",
      color: "chart-5",
      icon: Play,
      description: "Entry point of the workflow",
      config: { nodeType: "start" },
    },
    {
      blockId: "end",
      label: "End",
      type: "end",
      color: "chart-5",
      icon: CheckCircle2,
      description: "Termination point of the workflow",
      config: { nodeType: "end" },
    },
  ],

  Actors: [
    {
      blockId: "client",
      label: "Client",
      type: "actor",
      color: "chart-4",
      icon: User,
      description: "Ticket requester / end user",
      config: { nodeType: "actor", agentLevel: "client" },
    },
    {
      blockId: "l1-tech",
      label: "L1 Technician",
      type: "actor",
      color: "chart-4",
      icon: Headphones,
      description: "First level support - initial triage",
      config: { nodeType: "actor", agentLevel: "l1" },
    },
    {
      blockId: "l2-tech",
      label: "L2 Technician",
      type: "actor",
      color: "chart-4",
      icon: UserCog,
      description: "Second level support - advanced troubleshooting",
      config: { nodeType: "actor", agentLevel: "l2" },
    },
    {
      blockId: "l3-specialist",
      label: "L3 Specialist",
      type: "actor",
      color: "chart-4",
      icon: Cpu,
      description: "Third level support - developer / vendor escalation",
      config: { nodeType: "actor", agentLevel: "l3" },
    },
    {
      blockId: "supervisor",
      label: "Supervisor",
      type: "actor",
      color: "chart-4",
      icon: ShieldCheck,
      description: "Manager with approval authority",
      config: { nodeType: "actor", agentLevel: "supervisor" },
    },
  ],

  "Logic Blocks": [
    {
      blockId: "decision-manual",
      label: "Manual Decision",
      type: "decision",
      color: "chart-3",
      icon: GitBranch,
      description: "Pauses workflow for human decision (Approve/Reject)",
      config: {
        nodeType: "decision",
        decisionType: "manual",
        outcomes: [],
      },
    },
    {
      blockId: "decision-rule-based",
      label: "Rule-Based Decision",
      type: "decision",
      color: "chart-3",
      icon: GitBranch,
      description: "Automatic routing based on ticket data",
      config: {
        nodeType: "decision",
        decisionType: "rule-based",
        outcomes: [],
      },
    },
    {
      blockId: "condition-category",
      label: "Check Category",
      type: "condition",
      color: "chart-3",
      icon: Filter,
      description: "Branch based on ticket category (incident/service-request)",
      config: { nodeType: "condition" },
    },
    {
      blockId: "condition-impact",
      label: "Check Impact",
      type: "condition",
      color: "chart-3",
      icon: Filter,
      description: "Branch based on business impact",
      config: { nodeType: "condition" },
    },
  ],

  Automation: [
    {
      blockId: "business-rules",
      label: "Business Rules",
      type: "automation",
      color: "chart-2",
      icon: SlidersHorizontal,
      description:
        "Apply business rules (priority calculation, category mapping)",
      config: { nodeType: "automation", automationType: "business-rules" },
    },
    {
      blockId: "auto-assign",
      label: "Auto Assignment",
      type: "automation",
      color: "chart-2",
      icon: Shuffle,
      description: "Automatically assign ticket to first available Technician",
      config: {
        nodeType: "automation",
        automationType: "auto-assign",
        assignTo: "l1",
      },
    },
    {
      blockId: "sla-timer",
      label: "SLA Timer",
      type: "automation",
      color: "chart-2",
      description: "Start SLA timer for ticket",
      icon: Clock,
      config: {
        nodeType: "automation",
        automationType: "sla-timer",
        duration: 60,
      },
    },
    {
      blockId: "escalation",
      label: "Escalation",
      type: "automation",
      color: "chart-2",
      icon: ArrowUpCircle,
      description: "Escalate ticket",
      config: { nodeType: "automation", automationType: "escalation" },
    },
    {
      blockId: "notify",
      label: "Notification",
      type: "automation",
      color: "chart-2",
      icon: Bell,
      description: "Send notification to client/supervisor",
      config: {
        nodeType: "automation",
        automationType: "notify",
        channel: "email",
      },
    },
    {
      blockId: "reopen",
      label: "Reopen Ticket",
      type: "automation",
      color: "chart-2",
      icon: RotateCcw,
      description: "Reopen a previously resolved/closed ticket",
      config: { nodeType: "automation", automationType: "reopen" },
    },
  ],

  Actions: [
    {
      blockId: "resolve",
      label: "Resolve Ticket",
      type: "action",
      color: "chart-1",
      icon: CheckCircle,
      description: "Mark ticket as resolved (solution provided)",
      config: { nodeType: "action", ticketAction: "resolve" },
    },
    {
      blockId: "validate",
      label: "Validate Ticket",
      type: "action",
      color: "chart-1",
      icon: MessageSquare,
      description: "Client validates if resolution is satisfactory",
      config: { nodeType: "action", ticketAction: "validate" },
    },
    {
      blockId: "close",
      label: "Close Ticket",
      type: "action",
      color: "chart-1",
      icon: CheckCircle2,
      description: "Permanently close the ticket",
      config: { nodeType: "action", ticketAction: "close" },
    },
  ],
};
