import { BlockDefinition } from "./types";
import {
  ArrowUpCircle,
  Bell,
  CheckCircle,
  CheckCircle2,
  Circle,
  Clock,
  Cpu,
  Filter,
  GitBranch,
  Headphones,
  MessageSquare,
  PauseCircle,
  Play,
  PlayCircle,
  RotateCcw,
  ShieldCheck,
  Shuffle,
  SlidersHorizontal,
  User,
  UserCog,
} from "lucide-react";
export const BLOCKS: Record<string, BlockDefinition[]> = {
  Other: [
    {
      blockId: "start",
      label: "Start",
      type: "start",
      color: "chart-5",
      icon: Play,
      config: { nodeType: "start" },
    },
    {
      blockId: "end",
      label: "End",
      type: "end",
      color: "chart-5",
      icon: CheckCircle2,
      config: { nodeType: "end" },
    },
  ],

  Actors: [
    {
      blockId: "client",
      label: "Client",
      type: "actor",
      color: "chart-4",
      icon: User,
      config: { nodeType: "actor", agentLevel: "client" },
    },
    {
      blockId: "l1-tech",
      label: "L1 Technician",
      type: "actor",
      color: "chart-4",
      icon: Headphones,
      config: { nodeType: "actor", agentLevel: "l1" },
    },
    {
      blockId: "l2-tech",
      label: "L2 Technician",
      type: "actor",
      color: "chart-4",
      icon: UserCog,
      config: { nodeType: "actor", agentLevel: "l2" },
    },
    {
      blockId: "l3-specialist",
      label: "L3 Specialist",
      type: "actor",
      color: "chart-4",
      icon: Cpu,
      config: { nodeType: "actor", agentLevel: "l3" },
    },
    {
      blockId: "supervisor",
      label: "Supervisor",
      type: "actor",
      color: "chart-4",
      icon: ShieldCheck,
      config: { nodeType: "actor", agentLevel: "supervisor" },
    },
  ],

  "Logic Blocks": [
    {
      blockId: "decision",
      label: "Decision",
      type: "decision",
      color: "chart-3",
      icon: GitBranch,
      config: { nodeType: "decision", decisionType: "manual", outcomes: [] },
    },
    {
      blockId: "condition",
      label: "Condition",
      type: "condition",
      color: "chart-3",
      icon: Filter,
      config: { nodeType: "condition" },
    },
  ],

  Automation: [
    {
      blockId: "business-rules",
      label: "Business Rules",
      type: "automation",
      color: "chart-2",
      icon: SlidersHorizontal,
      config: { nodeType: "automation", automationType: "business-rules" },
    },
    {
      blockId: "auto-assign",
      label: "Auto Assignment",
      type: "automation",
      color: "chart-2",
      icon: Shuffle,
      config: {
        nodeType: "automation",
        automationType: "auto-assign",
        assignTo: "l1",
      },
    },
    {
      blockId: "sla-timer",
      label: "SLA Timer",
      type: "automation",
      color: "chart-2",
      icon: Clock,
      config: {
        nodeType: "automation",
        automationType: "sla-timer",
        duration: 60,
      },
    },
    {
      blockId: "escalation",
      label: "Escalation",
      type: "automation",
      color: "chart-2",
      icon: ArrowUpCircle,
      config: { nodeType: "automation", automationType: "escalation" },
    },
    {
      blockId: "notify",
      label: "Notification",
      type: "automation",
      color: "chart-2",
      icon: Bell,
      config: {
        nodeType: "automation",
        automationType: "notify",
        channel: "email",
      },
    },
    {
      blockId: "reopen",
      label: "Reopen Ticket",
      type: "automation",
      color: "chart-2",
      icon: RotateCcw,
      config: { nodeType: "automation", automationType: "reopen" },
    },
  ],

  Actions: [
    {
      blockId: "resolve",
      label: "Resolve Ticket",
      type: "action",
      color: "chart-1",
      icon: CheckCircle,
      config: { nodeType: "action", ticketAction: "resolve" },
    },
    {
      blockId: "validate",
      label: "Validate Ticket",
      type: "action",
      color: "chart-1",
      icon: MessageSquare,
      config: { nodeType: "action", ticketAction: "validate" },
    },
    {
      blockId: "close",
      label: "Close Ticket",
      type: "action",
      color: "chart-1",
      icon: CheckCircle2,
      config: { nodeType: "action", ticketAction: "close" },
    },
  ],
};
